[tool.poetry]
name = "nanapi"
version = "0.1.0"
description = ""
authors = [
    "NextFire <git@yuru.moe>",
    "odrling <florianbadie@odrling.xyz>",
    "Pierre Jeanjean <rhiobet@gmail.com>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Japan7/nanapi"

[tool.poetry.scripts]
nanapi = "nanapi.__main__:main"

[tool.poetry.dependencies]
python = "~3.12"
edgedb = "2.0.1"
fastapi = "0.112.1"
uvloop = "0.20.0"
pydantic = "2.8.2"
aiohttp = { version = "3.10.3", extras = ["speedups"] }
# https://github.com/PyYoshi/cChardet/issues/81
faust-cchardet = "2.1.19"
orjson = "3.10.7"
toolz = "0.12.1"
backoff = "2.2.1"
meilisearch-python-sdk = "3.1.0"
numpy = "2.0.1"
pillow = "10.4.0"
rich = "13.7.1"
discord-webhook = { version = "1.3.1", extras = ["async"] }
python-multipart = "0.0.9"
passlib = { version = "1.7.4", extras = ["bcrypt"] }
cachetools = "5.4.0"
asyncache = "0.3.1"
hypercorn = "0.17.3"
tzdata = "2024.1"
pyjwt = "2.9.0"

[tool.poetry.group.dev.dependencies]
pyright = "1.1.376"
ruff = "0.6.1"
edgedb-pydantic-codegen = "2024.8.2"
uvicorn = { version = "0.30.6", extras = ["standard"] }
pyinstrument = "4.7.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportDeprecated = true
ignore = [
    "nanapi/database", # FIXME: https://github.com/microsoft/pyright/issues/7228
]

[tool.ruff]
target-version = "py312"
line-length = 99
exclude = [
    "nanapi/database",
    "nanapi/nanachan_v2_migrate.py",
    "nanapi/local_settings.py",
]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "SIM", "I"]
ignore = [
    # lambda expressions
    "E731",
    # ambiguous variable name
    "E741",
    # Do not perform function calls in argument defaults
    "B008",
    # Within an except clause, raise exceptions with `raise ... from err` or `raise ... from None`
    "B904",
    # `zip()` without an explicit `strict=` parameter
    "B905",
    # Use `contextlib.suppress(asyncio.CancelledError)` instead of try-except-pass
    "SIM105",
    # Use ternary operator `{contents}` instead of if-else-block
    "SIM108",
]

[tool.ruff.format]
quote-style = "single"
